### PR TITLE
Bump Python requirements

### PR DESCRIPTION
**Pull request by marcovarrone**
I increased the maximum Python version from <3.10 to <3.11.
I run pytest and everything seems working smoothly.

### CODE REVIEW

**Comment by borchero** [comment]
We could actually get rid of the upper bound completely :smile:

**Comment by marcovarrone** [comment]
Maybe I was doing something wrong with the PyTorch installation, because I gave it only a quick check, but I tried to run some tests on Python 3.11 and it was failing with the following error:

`ValueError: mutable default <class 'torch.distributed._shard.sharded_tensor.metadata.TensorProperties'> for field tensor_properties is not allowed: use default_factory`

**Comment by borchero** [comment]
Oh ok, interesting 😅  I'll have a look as well.

**Comment by borchero** [comment]
Fixed in #2.

**Pull request closed without merging**
